### ISSUE TITLE
Encrypt and decrypt make the fonts corrupt

### ISSUE THREAD

**Issue by dangquang1020** [sjeedandi/gulp-protect#2]
I am developing an Angularjs web app, and use pdf.js library to build a pdf viewer.
Run at local it work well, but when I build production and enable gulp-protect task it seem makes the fonts corrupt.

pdf.js through an exception :

> Chrome Version 61.0.3163.79 (Official Build) (64-bit)
> Warning: Failed to load font "g_d2_f16": SyntaxError: Invalid font data in ArrayBuffer.

> Firefox 55.0.2 (64-bit)
>downloadable font: cmap: Range glyph reference too high (57344 > 39) (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64 ...
>downloadable font: rejected by sanitizer (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64 ...
>downloadable font: font load failed (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64 ...

This issue occur for some pdf file with special fonts.
Do you have any ideas for this issue, I have to disable gulp-protect temporary to ignore this issue.

**Comment by sjeedandi** [comment]
Only encrypt your application code and exclude vendor libraries.
